authentication/urls.py
from django.contrib import admin
from django.urls import path

from .views import LoginTemplate

urlpatterns = [
    path('', LoginTemplate.as_view(), name="login"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

from authentication.urls import urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include((urlpatterns, "authentication"), namespace="authentication"))
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render
# Create your views here.
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


class LoginTemplate(LoginView):
    template_name = "login.html"
    redirect_authenticated_user = True

core/templates/layout/base.html
{% load render_bundle from webpack_loader %}
{% load i18n static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    {% block extrastyle %}{% endblock %}
    {% render_bundle 'base' 'css'%}
    <meta charset="UTF-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
</head>

<body class="bg-grey-lighter h-screen font-sans">
    {% block messages %}
        {% if messages %}
        <ul class="messagelist">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message|capfirst }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endblock messages %}

    {% block content %}{% endblock content %}
    {% block footer %}<div id="footer"></div>{% endblock %}
</body>
{% render_bundle 'base' 'js'%}
{% render_bundle 'vendors' 'js'%}

</html>

core/templates/login.html
{% extends "layout/base.html" %}
{% load render_bundle from webpack_loader %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container mx-auto h-full flex justify-center items-center">
    <div class="w-1/3">
        <h1 class="font-hairline mb-6 text-center">Login to our Website</h1>
        {% if form.errors %}
            <p class="text-center text-red">El usuario o password no es válido.</p>
        {% endif %}
        
        {% if next %}
            {% if user.is_authenticated %}
            <p class="text-center text-red">Tu cuenta no tiene acceso a la página.</p>
            {% else %}
            <p class="text-center text-red">Inicie sesión para acceder a la página.</p>
            {% endif %}
        {% endif %}
        
        <form action={% url 'authentication:login' %} method="post">
            {% csrf_token %}
            <div class="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">{{form.username.label_tag}}</label>
                    <input type="text" name="username"
                        class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow"
                        placeholder="Your Username">
                </div>

                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">{{form.password.label_tag}}</label>
                    <input type="password" name="password"
                        class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow"
                        placeholder="Your Password">
                </div>
                <input type="hidden" name="next" value="{{ next }}">
                <div class="flex items-center justify-between">
                    <button class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Login
                    </button>

                    <a class="no-underline inline-block align-baseline font-bold text-sm text-blue hover:text-blue-dark float-right"
                        href="#">
                        Forgot Password?
                    </a>
                </div>

            </div>
            <div class="text-center">
                <p class="text-grey-dark text-sm">Don't have an account? <a href="#" class="no-underline text-blue font-bold">Create an Account</a>.</p>
            </div>
        </form>
    </div>
</div>
{% endblock content %}